nomatches:
- contains: "What version of World of Warcraft are are you running?" # Checks the entire issue for a substring match.
  addLabels: ["\U0001F41B Bug"]

- contains: "Is your feature request related to a problem? Please describe."
  addLabels: ["\U0001F3A8 Feature Request"]

tags:
- noneIn: ["\U0001F41B Bug", "\U0001F3A8 Feature Request"]
  addLabels: ["\U000023F1 Awaiting Response"]
