-- AUTO-GENERATED by Tools/generate-changelog-manifest.lua. Do not edit by hand;
-- run `lua Tools/generate-changelog-manifest.lua` (or `make changelog`) after editing
-- changelog.txt, then commit the result.
local personalPlayerNotes = ...

PersonalPlayerNotes.Changelog = "Prepared WoW 12.1.5 Retail compatibility (interface bump ships when patch is live).\
Added settings to control where the Add/Edit Listed Player context menu entry shows up: Party & Raid members, Friends list, and Chat."
