-- AUTO-GENERATED by Tools/generate-changelog-manifest.lua. Do not edit by hand;
-- run `lua Tools/generate-changelog-manifest.lua` (or `make changelog`) after editing
-- changelog.txt, then commit the result.
local personalPlayerNotes = ...

PersonalPlayerNotes.Changelog = "Fixed an issue where sound was played when selected."