-- AUTO-GENERATED by Tools/generate-sounds-manifest.lua. Do not edit by hand;
-- run `lua Tools/generate-sounds-manifest.lua` (or `make sounds`) after adding,
-- removing or renaming a file in Sounds/, then commit the result.
local personalPlayerNotes = ...

PersonalPlayerNotes.SoundManifest = {
    "default.mp3",
}
