name: Bug Report
description: File a bug report
title: "🐛 "
labels: ["🐛 Bug"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please [search for existing issues](https://github.com/Limmek/Shitlist/issues) to see if an open or closed one already exists for the bug you encountered. If a bug exists and it is closed you can create a new bug report.
      options:
      - label: I have searched the existing open and closed issues.
        required: true

  - type: textarea
    attributes:
      label: Description
      description: What did you expect to happen and what happened instead?
    validations:
      required: true

  - type: dropdown
    id: flavor
    attributes:
      label: World of Warcraft Flavor
      description: What version of World of Warcraft are are you running?
      options:
        - Retail (Default)
        - Classic
    validations:
      required: true
  
  - type: checkboxes
    id: testing
    attributes:
      label: Tested with only Personal Player Notes
      description: Did you try having Personal Player Notes as the only enabled addon and everything else disabled?
      options:
      - label: "Yes"
        required: true
  
  - type: textarea
    attributes:
      label: Lua Error
      description: |
        Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://www.curseforge.com/wow/addons/bugsack) & [BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber), yes both are needed.
      render: Text
    validations:
      required: false

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Please list out the steps to reproduce your bug. Please verify that your reproduction steps are enough to reproduce the problem.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Click here to attach your screenshots via the editor button in the top right.
    validations:
      required: false
