--[[
    Regenerates Sounds/Manifest.lua from the actual contents of Sounds/.

    WoW addons can't list a directory at runtime (no filesystem API exposed
    to the sandboxed client Lua), so the addon can't "dynamically" discover
    new .mp3/.ogg files while the game is running. Instead, this script runs
    outside the client (pure Lua 5.1, like Tools/validate-toc.lua) at
    development/packaging time: drop a new sound file into Sounds/, run this
    script (or `make sounds`), commit the regenerated Sounds/Manifest.lua,
    and the new file shows up as a selectable alert sound in-game.

    Usage:
        lua5.1 Tools/generate-sounds-manifest.lua           -- write Sounds/Manifest.lua
        lua5.1 Tools/generate-sounds-manifest.lua --check    -- verify it's already up to date (CI), no write

    Exits 0 on success (or an up-to-date --check), 1 on failure/out-of-date.
]]

local DEFAULT_SOUND = "default.mp3"

local function scriptDir()
    local source = debug.getinfo(1, "S").source:sub(2)
    return source:match("^(.*)[/\\][^/\\]+$") or "."
end

-- Repo root is the parent of this script's directory (Tools/../).
local repoRoot = scriptDir() .. "/.."
local soundsDir = repoRoot .. "/Sounds"
local manifestPath = soundsDir .. "/Manifest.lua"

local function findSoundFiles()
    local files = {}
    -- io.popen isn't guaranteed everywhere, but is available on the GitHub
    -- Actions runners and typical local dev machines this targets (same
    -- approach as Tools/validate-toc.lua's findTocFiles()). Pick the right
    -- listing command up front instead of probing with the Windows form and
    -- falling back on empty output: on Linux, GNU coreutils ships its own
    -- unrelated `dir` command, so `dir /b "<path>"` doesn't fail empty like
    -- it does on Windows - `/b` and the path are parsed as two separate
    -- operands, the path one succeeds, and `dir` prints a multi-column,
    -- space-separated listing (plus a header) that gets misread as a single
    -- bogus file name instead of triggering the POSIX fallback.
    local isWindows = package.config:sub(1, 1) == "\\"
    local list = isWindows and io.popen('dir /b "' .. soundsDir .. '" 2>nul')
        or io.popen('ls -1 "' .. soundsDir .. '" 2>/dev/null')
    if list then
        for line in list:lines() do
            files[#files + 1] = line
        end
        list:close()
    end

    local sounds = {}
    for _, name in ipairs(files) do
        if name:match("%.[Mm][Pp]3$") or name:match("%.[Oo][Gg][Gg]$") then
            sounds[#sounds + 1] = name
        end
    end

    -- default.mp3 always sorts first (the addon's default alert sound);
    -- everything else is alphabetical (case-insensitive) after it.
    table.sort(sounds, function(a, b)
        if a == DEFAULT_SOUND then
            return b ~= DEFAULT_SOUND
        end
        if b == DEFAULT_SOUND then
            return false
        end
        return a:lower() < b:lower()
    end)

    return sounds
end

local function renderManifest(sounds)
    local lines = {
        "-- AUTO-GENERATED by Tools/generate-sounds-manifest.lua. Do not edit by hand;",
        "-- run `lua Tools/generate-sounds-manifest.lua` (or `make sounds`) after adding,",
        "-- removing or renaming a file in Sounds/, then commit the result.",
        "local personalPlayerNotes = ...",
        "",
        "PersonalPlayerNotes.SoundManifest = {",
    }
    for _, name in ipairs(sounds) do
        lines[#lines + 1] = string.format('    "%s",', name)
    end
    lines[#lines + 1] = "}"
    lines[#lines + 1] = ""
    return table.concat(lines, "\n")
end

local function readFile(path)
    local f = io.open(path, "rb")
    if not f then
        return nil
    end
    local content = f:read("*a")
    f:close()
    return content
end

local function writeFile(path, content)
    local f = assert(io.open(path, "wb"))
    f:write(content)
    f:close()
end

local sounds = findSoundFiles()
if #sounds == 0 then
    io.stderr:write("generate-sounds-manifest: found no .mp3/.ogg files in Sounds/\n")
    os.exit(1)
end

local rendered = renderManifest(sounds)
local checkOnly = arg and arg[1] == "--check"

if checkOnly then
    local existing = readFile(manifestPath)
    if existing ~= rendered then
        io.stderr:write(
            "generate-sounds-manifest --check: Sounds/Manifest.lua is out of date.\n"
                .. "Run `lua Tools/generate-sounds-manifest.lua` (or `make sounds`) and commit the result.\n"
        )
        os.exit(1)
    end
    print("Sounds/Manifest.lua is up to date (" .. #sounds .. " sound files).")
    os.exit(0)
end

writeFile(manifestPath, rendered)
print("Wrote Sounds/Manifest.lua with " .. #sounds .. " sound files.")
