--[[
    Regenerates ChangelogManifest.lua from the actual contents of changelog.txt.

    WoW addons can't read arbitrary files from disk at runtime (no filesystem
    API exposed to the sandboxed client Lua), so changelog.txt itself (the
    packager's manual-changelog source, see .pkgmeta) can't be shown directly
    in a Blizzard options panel. Instead, this script runs outside the client
    (pure Lua 5.1, like Tools/validate-toc.lua) at development/
    packaging time: edit changelog.txt, run this script (or `make changelog`),
    commit the regenerated ChangelogManifest.lua, and the new text shows up in
    the addon's "Changelog" options panel.

    Usage:
        lua5.1 Tools/generate-changelog-manifest.lua           -- write ChangelogManifest.lua
        lua5.1 Tools/generate-changelog-manifest.lua --check    -- verify it's already up to date (CI), no write

    Exits 0 on success (or an up-to-date --check), 1 on failure/out-of-date.
]]

local function scriptDir()
    local source = debug.getinfo(1, "S").source:sub(2)
    return source:match("^(.*)[/\\][^/\\]+$") or "."
end

-- Repo root is the parent of this script's directory (Tools/../).
local repoRoot = scriptDir() .. "/.."
local changelogPath = repoRoot .. "/changelog.txt"
local manifestPath = repoRoot .. "/ChangelogManifest.lua"

local function readFile(path)
    local f = io.open(path, "rb")
    if not f then
        return nil
    end
    local content = f:read("*a")
    f:close()
    return content
end

local function writeFile(path, content)
    local f = assert(io.open(path, "wb"))
    f:write(content)
    f:close()
end

local function renderManifest(changelog)
    -- Normalize CRLF -> LF first: changelog.txt is typically edited/saved
    -- with Windows line endings, but a bare "\r" embedded in the resulting
    -- Lua string doesn't reliably render as a line break in WoW's FontString
    -- widgets (only "\n" does), so it must not survive into the manifest.
    local normalized = changelog:gsub("\r\n", "\n"):gsub("\r", "\n")
    -- Trim trailing whitespace/newlines so re-running this script doesn't
    -- keep growing the string with an extra blank line every time.
    local trimmed = normalized:gsub("%s+$", "")
    local lines = {
        "-- AUTO-GENERATED by Tools/generate-changelog-manifest.lua. Do not edit by hand;",
        "-- run `lua Tools/generate-changelog-manifest.lua` (or `make changelog`) after editing",
        "-- changelog.txt, then commit the result.",
        "local personalPlayerNotes = ...",
        "",
        "PersonalPlayerNotes.Changelog = " .. string.format("%q", trimmed),
        "",
    }
    return table.concat(lines, "\n")
end

local changelog = readFile(changelogPath)
if not changelog or changelog:match("^%s*$") then
    io.stderr:write("generate-changelog-manifest: changelog.txt is missing or empty\n")
    os.exit(1)
end

local rendered = renderManifest(changelog)
local checkOnly = arg and arg[1] == "--check"

if checkOnly then
    local existing = readFile(manifestPath)
    if existing ~= rendered then
        io.stderr:write(
            "generate-changelog-manifest --check: ChangelogManifest.lua is out of date.\n"
                .. "Run `lua Tools/generate-changelog-manifest.lua` (or `make changelog`) and commit the result.\n"
        )
        os.exit(1)
    end
    print("ChangelogManifest.lua is up to date.")
    os.exit(0)
end

writeFile(manifestPath, rendered)
print("Wrote ChangelogManifest.lua from changelog.txt.")
