name: Update TOC Interface version(s)

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *

jobs:
  run:
    name: TOCcheck
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v6
      
      - name: Checking Vanilla
        uses: p3lim/toc-interface-updater@v4
        with:
          flavor: vanilla

      - name: Checking Wrath
        uses: p3lim/toc-interface-updater@v4
        with:
          flavor: wrath

      - name: Checking Mists
        uses: p3lim/toc-interface-updater@v4
        with:
          flavor: mists

      - name: Checking Retail
        uses: p3lim/toc-interface-updater@v4
        with:
          flavor: retail
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v10
        with:
          message: 'Update TOC interface version(s)'
          add: '.'
