name: Update TOC Interface version(s)

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    name: TOCcheck
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v6

      - name: Update TOC Interface versions
        uses: p3lim/toc-interface-updater@v4
        with:
          flavor: retail

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'Update TOC interface version(s)'
          branch: 'ci/toc-interface-update'
          delete-branch: true
          title: 'Update TOC interface version(s)'
          body: 'Automated TOC interface version update.'
          labels: 'maintenance'
