name: Update TOC Interface version(s)

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  # workflow_run:
  #     workflows: ['Luacheck']
  #     types:
  #       - completed
  # schedule:
  #   - cron: 0 12 * * *

jobs:
  run:
    name: TOCcheck
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      
      - name: Checking Vanilla
        uses: p3lim/toc-interface-updater@v4
        with:
          flavor: vanilla
          future: true

      - name: Checking Wrath
        uses: p3lim/toc-interface-updater@v4
        with:
          flavor: wrath
          future: true

      - name: Checking Cata
        uses: p3lim/toc-interface-updater@v4
        with:
          flavor: cata
          future: true

      - name: Checking Retail
        uses: p3lim/toc-interface-updater@v4
        with:
          flavor: retail
          future: true
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update TOC interface version(s)'
          add: '.'
